services:
  db:
    image: postgres:16-alpine
    container_name: beacon-db
    environment:
      POSTGRES_USER: beacon
      POSTGRES_PASSWORD: beacon
      POSTGRES_DB: beacon
    ports:
      - "5432:5432"
    volumes:
      - beacon-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beacon -h localhost -d beacon"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  api:
    build: .
    container_name: beacon-api
    environment:
      BATABASE_URL: postgresql+psycopg://beacon:beacon@db:5432/beacon
    ports:
      - "8000:8000"
    depends_on:
     db:
      condition: service_healthy
    volumes:
      - ./app:/app/app

volumes:
  beacon-db-data: